export const categorias = [
  {value: "food", label: "Alimentos"},
  {value: "environment", label: "Ambientales"},
  {value: "science", label: "Ciencia"},
  {value: "crime", label: "Criminales"},
  {value: "sports", label: "Deportes"},
  {value: "education", label: "Educación"},
  {value: "entertainment", label: "Entretenimiento"},
  {value: "lifestyle", label: "Estilo de vida"},
  {value: "domestic", label: "Hogar"},
  {value: "world", label: "Internacionales"},
  {value: "top", label: "Más vistas"},
  {value: "business", label: "Negocios"},
  {value: "politics", label: "Política"},
  {value: "health", label: "Salud"},
  {value: "technology", label: "Tecnología"},
  {value: "tourism", label: "Turismo"},
  {value: "other", label: "Otras"}
]

export const paises = [
  {value: "af", label: "Afganistán"},
  {value: "al", label: "Albania"},
  {value: "de", label: "Alemania"},
  {value: "ad", label: "Andorra"},
  {value: "ao", label: "Angola"},
  {value: "sa", label: "Arabia Saudita"},
  {value: "dz", label: "Argelia"},
  {value: "ar", label: "Argentina"},
  {value: "am", label: "Armenia"},
  {value: "au", label: "Australia"},
  {value: "at", label: "Austria"},
  {value: "az", label: "Azerbaiyán"},
  {value: "bs", label: "Bahamas"},
  {value: "bd", label: "Bangladesh"},
  {value: "bb", label: "Barbados"},
  {value: "bh", label: "Baréin"},
  {value: "be", label: "Bélgica"},
  {value: "bz", label: "Belice"},
  {value: "bj", label: "Benín"},
  {value: "bm", label: "Bermudas"},
  {value: "by", label: "Bielorrusia"},
  {value: "bo", label: "Bolivia"},
  {value: "ba", label: "Bosnia y Herzegovina"},
  {value: "bw", label: "Botsuana"},
  {value: "br", label: "Brasil"},
  {value: "bn", label: "Brunéi"},
  {value: "bg", label: "Bulgaria"},
  {value: "bf", label: "Burkina Faso"},
  {value: "bi", label: "Burundi"},
  {value: "bt", label: "Bután"},
  {value: "cv", label: "Cabo Verde"},
  {value: "kh", label: "Camboya"},
  {value: "cm", label: "Camerún"},
  {value: "ca", label: "Canadá"},
  {value: "td", label: "Chad"},
  {value: "cl", label: "Chile"},
  {value: "cn", label: "China"},
  {value: "cy", label: "Chipre"},
  {value: "co", label: "Colombia"},
  {value: "km", label: "Comoras"},
  {value: "cg", label: "Congo"},
  {value: "kp", label: "Corea del Norte"},
  {value: "kr", label: "Corea del Sur"},
  {value: "ci", label: "Costa de Marfil"},
  {value: "cr", label: "Costa Rica"},
  {value: "hr", label: "Croacia"},
  {value: "cu", label: "Cuba"},
  {value: "dk", label: "Dinamarca"},
  {value: "dm", label: "Dominica"},
  {value: "ec", label: "Ecuador"},
  {value: "eg", label: "Egipto"},
  {value: "sv", label: "El Salvador"},
  {value: "ae", label: "Emiratos Árabes Unidos"},
  {value: "er", label: "Eritrea"},
  {value: "sk", label: "Eslovaquia"},
  {value: "si", label: "Eslovenia"},
  {value: "es", label: "España"},
  {value: "us", label: "Estados Unidos"},
  {value: "ee", label: "Estonia"},
  {value: "et", label: "Etiopía"},
  {value: "fj", label: "Fiji"},
  {value: "ph", label: "Filipinas"},
  {value: "fi", label: "Finlandia"},
  {value: "fr", label: "Francia"},
  {value: "ga", label: "Gabón"},
  {value: "gm", label: "Gambia"},
  {value: "ge", label: "Georgia"},
  {value: "gh", label: "Ghana"},
  {value: "gd", label: "Granada"},
  {value: "gr", label: "Grecia"},
  {value: "gt", label: "Guatemala"},
  {value: "gn", label: "Guinea"},
  {value: "gq", label: "Guinea Ecuatorial"},
  {value: "gy", label: "Guyana"},
  {value: "ht", label: "Haití"},
  {value: "hn", label: "Honduras"},
  {value: "hk", label: "Hong Kong"},
  {value: "hu", label: "Hungría"},
  {value: "in", label: "India"},
  {value: "id", label: "Indonesia"},
  {value: "ir", label: "Irán"},
  {value: "iq", label: "Irak"},
  {value: "ie", label: "Irlanda"},
  {value: "is", label: "Islandia"},
  {value: "ky", label: "Islas Caimán"},
  {value: "mh", label: "Islas Marshall"},
  {value: "sb", label: "Islas Solomon"},
  {value: "il", label: "Israel"},
  {value: "it", label: "Italia"},
  {value: "jm", label: "Jamaica"},
  {value: "jp", label: "Japón"},
  {value: "jo", label: "Jordania"},
  {value: "kz", label: "Kazajistán"},
  {value: "ke", label: "Kenia"},
  {value: "ki", label: "Kiribati"},
  {value: "xk", label: "Kosovo"},
  {value: "kw", label: "Kuwait"},
  {value: "kg", label: "Kirguistán"},
  {value: "la", label: "Laos"},
  {value: "ls", label: "Lesoto"},
  {value: "lv", label: "Letonia"},
  {value: "lb", label: "Líbano"},
  {value: "lr", label: "Liberia"},
  {value: "ly", label: "Libia"},
  {value: "li", label: "Liechtenstein"},
  {value: "lt", label: "Lituania"},
  {value: "lu", label: "Luxemburgo"},
  {value: "mk", label: "Macedonia"},
  {value: "mg", label: "Madagascar"},
  {value: "mw", label: "Malaui"},
  {value: "my", label: "Malasia"},
  {value: "mv", label: "Maldivas"},
  {value: "ml", label: "Mali"},
  {value: "mt", label: "Malta"},
  {value: "ma", label: "Marruecos"},
  {value: "mu", label: "Mauricio"},
  {value: "mr", label: "Mauritania"},
  {value: "mx", label: "México"},
  {value: "fm", label: "Micronesia"},
  {value: "md", label: "Moldavia"},
  {value: "mc", label: "Mónaco"},
  {value: "mn", label: "Mongolia"},
  {value: "me", label: "Montenegro"},
  {value: "mz", label: "Mozambique"},
  {value: "mm", label: "Myanmar"},
  {value: "na", label: "Namibia"},
  {value: "nr", label: "Nauru"},
  {value: "np", label: "Nepal"},
  {value: "ni", label: "Nicaragua"},
  {value: "ne", label: "Níger"},
  {value: "ng", label: "Nigeria"},
  {value: "no", label: "Noruega"},
  {value: "nz", label: "Nueva Zelanda"},
  {value: "om", label: "Omán"},
  {value: "nl", label: "Países Bajos"},
  {value: "pk", label: "Pakistán"},
  {value: "pw", label: "Palaos"},
  {value: "pa", label: "Panamá"},
  {value: "pg", label: "Papúa Nueva Guinea"},
  {value: "py", label: "Paraguay"},
  {value: "pe", label: "Perú"},
  {value: "pf", label: "Polinesia Francesa"},
  {value: "pl", label: "Polonia"},
  {value: "pt", label: "Portugal"},
  {value: "pr", label: "Puerto Rico"},
  {value: "qa", label: "Qatar"},
  {value: "gb", label: "Reino Unido"},
  {value: "cf", label: "República Centroafricana"},
  {value: "cz", label: "República Checa"},
  {value: "cd", label: "República Democrática del Congo"},
  {value: "do", label: "República Dominicana"},
  {value: "rw", label: "Ruanda"},
  {value: "ro", label: "Rumania"},
  {value: "ru", label: "Rusia"},
  {value: "ws", label: "Samoa"},
  {value: "sm", label: "San Marino"},
  {value: "sn", label: "Senegal"},
  {value: "rs", label: "Serbia"},
  {value: "sc", label: "Seychelles"},
  {value: "sl", label: "Sierra Leona"},
  {value: "sg", label: "Singapur"},
  {value: "sy", label: "Siria"},
  {value: "so", label: "Somalia"},
  {value: "za", label: "Sudáfrica"},
  {value: "lk", label: "Sri Lanka"},
  {value: "sz", label: "Suazilandia"},
  {value: "sd", label: "Sudán"},
  {value: "se", label: "Suecia"},
  {value: "ch", label: "Suiza"},
  {value: "sr", label: "Suriname"},
  {value: "th", label: "Tailandia"},
  {value: "tw", label: "Taiwán"},
  {value: "tz", label: "Tanzania"},
  {value: "tj", label: "Tayikistán"},
  {value: "tl", label: "Timor Oriental"},
  {value: "tg", label: "Togo"},
  {value: "to", label: "Tonga"},
  {value: "tn", label: "Túnez"},
  {value: "tr", label: "Turquía"},
  {value: "tm", label: "Turkmenistán"},
  {value: "tv", label: "Tuvalu"},
  {value: "ua", label: "Ucrania"},
  {value: "ug", label: "Uganda"},
  {value: "uy", label: "Uruguay"},
  {value: "uz", label: "Uzbekistán"},
  {value: "vu", label: "Vanuatu"},
  {value: "va", label: "Vaticano"},
  {value: "ve", label: "Venezuela"},
  {value: "vn", label: "Vietnam"},
  {value: "wo", label: "Internacional"},
  {value: "ye", label: "Yemen"},
  {value: "dj", label: "Yibuti"},
  {value: "zm", label: "Zambia"},
  {value: "zw", label: "Zimbabue"}
]